export const mockRescueTeams = [
  {
    id: "TEAM-NDRF-10",
    name: "NDRF Battalion 10 (Specialized Water Rescue)",
    commander: "Commandant A. K. Varma",
    baseStation: "Hyderabad Control Hub",
    type: "NDRF",
    status: "ON_DISPATCH",
    assignedVictimId: "VIC-8822",
    members: 18,
    motorboats: 4,
    lifeJacketCount: 65,
    satellitePhone: "+91 88001 99110",
    lat: 17.4100,
    lng: 78.4500,
    etaMinutes: 12
  },
  {
    id: "TEAM-SDRF-04",
    name: "SDRF Telangana Inflatable Boat Unit 4",
    commander: "Inspector M. Rajesham",
    baseStation: "Begumpet Fire Base",
    type: "SDRF",
    status: "AVAILABLE",
    assignedVictimId: null,
    members: 12,
    motorboats: 3,
    lifeJacketCount: 40,
    satellitePhone: "+91 88001 99114",
    lat: 17.4350,
    lng: 78.4720,
    etaMinutes: 5
  },
  {
    id: "TEAM-FIRE-02",
    name: "Telangana State Fire & Heavy Evacuation Force 2",
    commander: "Chief Officer D. Srinivas",
    baseStation: "Secunderabad Fire HQ",
    type: "FIRE",
    status: "ON_DISPATCH",
    assignedVictimId: "VIC-8821",
    members: 15,
    heavyTrucks: 2,
    dewateringPumps: 6,
    satellitePhone: "+91 88001 99116",
    lat: 17.4399,
    lng: 78.4983,
    etaMinutes: 8
  },
  {
    id: "TEAM-AIR-01",
    name: "Indian Air Force Mi-17V5 Airlift Squadron",
    commander: "Wing Commander S. Roy",
    baseStation: "Hakimpet AFS",
    type: "AIR_FORCE",
    status: "STANDBY",
    assignedVictimId: null,
    members: 8,
    helicopters: 2,
    winchingKits: 4,
    satellitePhone: "+91 88001 99199",
    lat: 17.5522,
    lng: 78.5255,
    etaMinutes: 15
  }
];
