export const initialVictims = [
  {
    id: "VIC-8821",
    name: "Ramesh Sharma",
    phone: "+91 98490 12345",
    aadhaar: "XXXX-XXXX-8912",
    lat: 17.3850,
    lng: 78.4867,
    city: "Hyderabad (Hitec City / Begumpet)",
    state: "Telangana",
    level: "red", // red, orange, yellow, green
    status: "CRITICAL",
    battery: 14,
    network: "1 Bar (3G)",
    lastSeen: "2 mins ago",
    waterDepthMeters: 2.4,
    waitTimeMinutes: 45,
    age: 68,
    isSenior: true,
    isChild: false,
    isPregnant: false,
    isDisabled: true,
    medicalConditions: "Heart Patient, Severe Mobility Issue",
    bloodGroup: "O+",
    emergencyContact: "Anitha (Daughter) +91 98490 54321",
    assignedTeam: null,
    movementDetected: false
  },
  {
    id: "VIC-8822",
    name: "Priya Sundaram",
    phone: "+91 94440 98765",
    aadhaar: "XXXX-XXXX-4531",
    lat: 11.6643,
    lng: 76.1320,
    city: "Wayanad (Meppadi)",
    state: "Kerala",
    level: "red",
    status: "URGENT",
    battery: 28,
    network: "2 Bars (4G)",
    lastSeen: "Just now",
    waterDepthMeters: 1.8,
    waitTimeMinutes: 90,
    age: 29,
    isSenior: false,
    isChild: true,
    isPregnant: true,
    isDisabled: false,
    medicalConditions: "8 Months Pregnant with 4yo Child",
    bloodGroup: "B+",
    emergencyContact: "Karthik (Husband) +91 94440 11223",
    assignedTeam: "NDRF Battalion 4",
    movementDetected: true
  },
  {
    id: "VIC-8823",
    name: "Subhash Patnaik",
    phone: "+91 97771 22334",
    aadhaar: "XXXX-XXXX-7788",
    lat: 20.4625,
    lng: 85.8828,
    city: "Cuttack (Mahanadi River Basin)",
    state: "Odisha",
    level: "orange",
    status: "WAITING",
    battery: 52,
    network: "3 Bars (4G)",
    lastSeen: "5 mins ago",
    waterDepthMeters: 1.1,
    waitTimeMinutes: 30,
    age: 42,
    isSenior: false,
    isChild: false,
    isPregnant: false,
    isDisabled: false,
    medicalConditions: "Minor Leg Laceration",
    bloodGroup: "A+",
    emergencyContact: "Sulata (Wife) +91 97771 99887",
    assignedTeam: null,
    movementDetected: true
  },
  {
    id: "VIC-8824",
    name: "Sunita Deshmukh",
    phone: "+91 98200 44556",
    aadhaar: "XXXX-XXXX-1122",
    lat: 19.0760,
    lng: 72.8777,
    city: "Mumbai (Kurla West)",
    state: "Maharashtra",
    level: "red",
    status: "CRITICAL",
    battery: 8,
    network: "No Signal (Offline Queue)",
    lastSeen: "12 mins ago",
    waterDepthMeters: 2.1,
    waitTimeMinutes: 110,
    age: 74,
    isSenior: true,
    isChild: false,
    isPregnant: false,
    isDisabled: true,
    medicalConditions: "Requires Asthma Inhaler & Oxygen Support",
    bloodGroup: "AB+",
    emergencyContact: "Amit (Son) +91 98200 88990",
    assignedTeam: null,
    movementDetected: false
  },
  {
    id: "VIC-8825",
    name: "Barun Kalita",
    phone: "+91 94350 33445",
    aadhaar: "XXXX-XXXX-3344",
    lat: 26.1445,
    lng: 91.7362,
    city: "Guwahati (Kaziranga Buffer)",
    state: "Assam",
    level: "orange",
    status: "WAITING",
    battery: 64,
    network: "4 Bars (5G)",
    lastSeen: "1 min ago",
    waterDepthMeters: 1.5,
    waitTimeMinutes: 20,
    age: 35,
    isSenior: false,
    isChild: true,
    isPregnant: false,
    isDisabled: false,
    medicalConditions: "Safe on rooftop with 2 children",
    bloodGroup: "O-",
    emergencyContact: "Biren (Brother) +91 94350 77889",
    assignedTeam: "SDRF Assam Unit 2",
    movementDetected: true
  },
  {
    id: "VIC-8826",
    name: "Vijay Reddy",
    phone: "+91 98850 66778",
    aadhaar: "XXXX-XXXX-9900",
    lat: 16.5062,
    lng: 80.6480,
    city: "Vijayawada (Prakasam Barrage)",
    state: "Andhra Pradesh",
    level: "green",
    status: "SAFE",
    battery: 89,
    network: "Full 5G",
    lastSeen: "Just now",
    waterDepthMeters: 0.2,
    waitTimeMinutes: 0,
    age: 31,
    isSenior: false,
    isChild: false,
    isPregnant: false,
    isDisabled: false,
    medicalConditions: "Safe at relief camp",
    bloodGroup: "B-",
    emergencyContact: "Lakshmi +91 98850 11111",
    assignedTeam: null,
    movementDetected: true
  }
];
