export const mockShelters = [
  {
    id: "SHL-01",
    name: "Government High School Relief Camp (Hitec City)",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.4435,
    lng: 78.3772,
    capacity: 1200,
    occupiedBeds: 420,
    availableBeds: 780,
    foodStockDays: 5,
    waterLiters: 15000,
    medicalDoctorOnSite: true,
    distanceKm: 2.1,
    contact: "+91 040 2311 9900",
    facilities: ["Clean Water", "Medical Bay", "Power Generator", "Baby Food", "Sanitation Kits"]
  },
  {
    id: "SHL-02",
    name: "Nizam College Indoor Stadium Relief Hub",
    city: "Hyderabad (Abids)",
    state: "Telangana",
    lat: 17.3980,
    lng: 78.4740,
    capacity: 2500,
    occupiedBeds: 1890,
    availableBeds: 610,
    foodStockDays: 3,
    waterLiters: 28000,
    medicalDoctorOnSite: true,
    distanceKm: 4.8,
    contact: "+91 040 2320 1122",
    facilities: ["Helipad Access", "NDRF Command Post", "Blood Storage", "Community Kitchen"]
  },
  {
    id: "SHL-03",
    name: "St. Joseph Higher Secondary Shelter",
    city: "Wayanad (Kalpetta)",
    state: "Kerala",
    lat: 11.6087,
    lng: 76.0847,
    capacity: 800,
    occupiedBeds: 620,
    availableBeds: 180,
    foodStockDays: 4,
    waterLiters: 8500,
    medicalDoctorOnSite: true,
    distanceKm: 5.4,
    contact: "+91 04936 202 333",
    facilities: ["Landslide Evacuation Zone", "Ambulance Station", "Maternity Care"]
  },
  {
    id: "SHL-04",
    name: "Cuttack Municipal Corporation Convention Center",
    city: "Cuttack",
    state: "Odisha",
    lat: 20.4650,
    lng: 85.8790,
    capacity: 3000,
    occupiedBeds: 1200,
    availableBeds: 1800,
    foodStockDays: 7,
    waterLiters: 45000,
    medicalDoctorOnSite: true,
    distanceKm: 3.2,
    contact: "+91 0671 230 4455",
    facilities: ["Motorboat Dock", "Disaster Storage Depot", "VHF Radio Base"]
  },
  {
    id: "SHL-05",
    name: "Kurla Municipal High School Camp",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.0650,
    lng: 72.8790,
    capacity: 1500,
    occupiedBeds: 1110,
    availableBeds: 390,
    foodStockDays: 2,
    waterLiters: 12000,
    medicalDoctorOnSite: true,
    distanceKm: 1.8,
    contact: "+91 022 2650 9988",
    facilities: ["Pumping Station Nearby", "Dharavi Evac Center", "Emergency Medicine Depot"]
  }
];
